apiVersion: v1
kind: Service
metada:
  name: db
  labels:
    name: db
    app: app-votacion
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    name: "db-service"
  selector:
    name: db
    app: app-votacion