apiVersion: v1
kind: Service
metada:
  name: vote
  labels:
    name: vote
    app: app-votacion
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    #puerto al que podemos ingresar por localhost 31000
    nodePort: 31000
    name: "vote-service"
  selector:
    name: vote
    app: app-votacion